# Site settings
title: Code for Somewhere
email: somewhere@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Code for Somewhere is a Brigade that builds community and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-meetup

# Configuration settings for Jekyll Meetup plugin:
meetup:
  # download meetup events into the _data/events/ folder
  collection_name: events
  # fetch events for this meetup page (this is the part in the URL on Meetup)
  urlname: OpenOakland

exclude:
  - README.md
